// <auto-generated />
using System;
using EnterpriseProj.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EnterpriseProj.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250412231913_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EnterpriseProj.Entities.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClaimId")
                        .HasColumnType("int");

                    b.Property<int?>("ClientId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("bit");

                    b.Property<int?>("PractitionerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isBooked")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("PractitionerId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("EnterpriseProj.Entities.Claim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AppointmentId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId")
                        .IsUnique();

                    b.ToTable("Claims");
                });

            modelBuilder.Entity("EnterpriseProj.Entities.Job", b =>
                {
                    b.Property<int>("JobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JobId"));

                    b.Property<string>("JobName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("JobId");

                    b.ToTable("Jobs");

                    b.HasData(
                        new
                        {
                            JobId = 1,
                            JobName = "Physiotherapist"
                        },
                        new
                        {
                            JobId = 2,
                            JobName = "Psychologist"
                        },
                        new
                        {
                            JobId = 3,
                            JobName = "Chiropractor"
                        },
                        new
                        {
                            JobId = 4,
                            JobName = "Occupational Therapist"
                        },
                        new
                        {
                            JobId = 5,
                            JobName = "Non-Descript Massage Persons"
                        });
                });

            modelBuilder.Entity("EnterpriseProj.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("JobId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("EnterpriseProj.Entities.Appointment", b =>
                {
                    b.HasOne("EnterpriseProj.Entities.User", "Client")
                        .WithMany("ClientAppointments")
                        .HasForeignKey("ClientId");

                    b.HasOne("EnterpriseProj.Entities.User", "Practitioner")
                        .WithMany("PractitionerAppointments")
                        .HasForeignKey("PractitionerId");

                    b.Navigation("Client");

                    b.Navigation("Practitioner");
                });

            modelBuilder.Entity("EnterpriseProj.Entities.Claim", b =>
                {
                    b.HasOne("EnterpriseProj.Entities.Appointment", "Appointment")
                        .WithOne("Claim")
                        .HasForeignKey("EnterpriseProj.Entities.Claim", "AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appointment");
                });

            modelBuilder.Entity("EnterpriseProj.Entities.User", b =>
                {
                    b.HasOne("EnterpriseProj.Entities.Job", "Job")
                        .WithMany("Users")
                        .HasForeignKey("JobId");

                    b.Navigation("Job");
                });

            modelBuilder.Entity("EnterpriseProj.Entities.Appointment", b =>
                {
                    b.Navigation("Claim");
                });

            modelBuilder.Entity("EnterpriseProj.Entities.Job", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("EnterpriseProj.Entities.User", b =>
                {
                    b.Navigation("ClientAppointments");

                    b.Navigation("PractitionerAppointments");
                });
#pragma warning restore 612, 618
        }
    }
}
